name: duet
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - ipykernel
  - joblib==1.4.2
  - matplotlib
  - numpy=1.26.3
  - omegaconf
  - pandas=2.1.4
  - python=3.10.13
  - pytorch-cuda=12.1
  - pytorch=2.2.0
  - scikit-learn=1.2.1
  - scipy=1.10.1
  - torchvision=0.17.0
  - tqdm
  - wandb
  - pip:
    - pytorch-lightning==2.4.0
    - biopython==1.85
    - forgi
    - loguru
    - viennarna==2.7.0
    - captum==0.8.0
