dataset:
  train: benchmarks/datasets/te_prediction/PC3_sequence.tsv
  test: benchmarks/datasets/te_prediction/PC3_sequence.tsv
  param:
    sequence_feature_path: benchmarks/datasets/te_prediction/te_benchmark_data_sequence_features.tsv

datamodule:
  batch_size: 16

trainer:
  early_stopping: 12
